config/routes.rb
Rails.application.routes.draw do
  get 'pages/secret'
	root to: 'users#new'

	get 'users/new' => 'users#new', as: :new_user
	post 'users' => 'users#create'

	get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
	delete '/logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	helper_method :current_user

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	
	def authorize
		redirect_to login_path, 'alert': 'You must be logged in to access this page.' if current_user.nil?
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authorize, only: [:secret]
  def secret
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		user = User.find_by(email: params[:login][:email].downcase)
		if user && user.authenticate(params[:login][:password]) 
		 	session[:user_id] = user.id.to_s
    	redirect_to root_path, notice: 'Successfully logged in!'
		else
			flash.now.alert = "Incorrect email or password, try again."
      render :new
		end
	end
	def destroy
		session.delete(:user_id)
		redirect_to login_path, notice: "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		@user.email.downcase!

		# difference between flash[:notice] and flash.now[:notice]
		# -----
		# "Flash[:notice]‘s message will persist to the next
		# action and should be used when redirecting to
		# another action via the ‘redirect_to’ method.
		# -----
		# Flash.now[:notice]‘s message will be displayed in
		# the view your are rendering via the ‘render’
		# method."
		
		if @user.save
			flash[:notice] = "Account created"
			redirect_to root_path
		else
			flash.now.alert = "Could not create account"\
				"Make sure everything is correct"
			render :new
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorAuthPages</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <!-- current_user will return true if a user is logged in -->
    <%= "Logged in as #{current_user.email}" %> | 
    <%= link_to 'Home', root_path %> | <%= link_to 'Log Out', logout_path, method: :delete %>
    <% else %>
      <!-- not logged in -->
      <%= link_to 'Home', root_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_user_path %>
    <% end %>
    <hr>
    <!--notice is a shortcut to flash[:notice]
    alert is a shortcut to flash[:alert]-->
    <% if notice %>
      <%= notice %>
    <% end %>
    <% if alert %>
      <%= alert %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/secret.html.erb
<h1>Pages#secret</h1>
<p>Find me in app/views/pages/secret.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>